In [1]:
import numpy as np

### `numpy` basics

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
type(0)

int

In [13]:
type(0.)

float

In [14]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operaciones basicas con `numpy`

In [17]:
np.random.seed(101)

In [18]:
arr = np.random.randint(0,100,10)

In [19]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
arr2 = np.random.randint(0,100,10)

In [21]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [22]:
arr.max() # Valor maximo del array

95

In [23]:
arr.argmax() #indice del valor maximo del array

0

In [24]:
arr.min() # Valor minimo del array

9

In [26]:
arr.argmin() #indice del valor minimo del array

7

In [27]:
arr.mean() # media

60.8

In [28]:
arr.shape

(10,)

In [29]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [30]:
arr.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

## Indexing

In [31]:
mat = np.arange(0,100).reshape(10,10)

In [32]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
mat.shape

(10, 10)

In [37]:
row = 0
column = 1

In [38]:
mat[row,column]

1

In [39]:
mat[4,6]

46

In [42]:
mat[:,1] #slicing para solo columna

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [45]:
mat[2,:]#slicing para solo fila

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [48]:
mat[0:3,0:4] = 0
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mynewmat = mat.copy()

In [50]:
mynewmat[0:6,:] = 999
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])